name: Unit tests

on:
  pull_request:

jobs:
  build-and-test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v21.5.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
